### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Luchanso** [Luchanso/dota-helper#57]
- [x] Yarn 2.0
- [ ] Update dependencies
- [ ] Convert to Monorepo
- [ ] Dynamic configuration
- [ ] Автоконфигурация игры

- [ ] Migrate from REST to GraphQL (remove redux)

- [ ] Timing Coach update
  - [ ] Early spawn timings
  - [ ] Catapults
  - [ ] Stack timer
  - [ ] Bounty runes
  - [ ] Roshan Analize
- [ ] Daytime Changed - Time to Gang / Placing wards
- [ ] Item build Recommendation
- [ ] Analyze - can we deny tower?
- [ ] Current net worse
- [ ] Аналитика по контрпику
- [ ] Ability Build Stats

- [ ] Screen capture
- [ ] Analize Rosh message
